import { useState, useEffect } from "react";
import {
  HiOutlineChevronLeft,
  HiOutlineChevronRight,
  HiOutlineMagnifyingGlass,
  HiOutlinePencilSquare,
  HiOutlineCheckCircle,
  HiOutlineExclamationCircle,
  HiOutlineXMark,
} from "react-icons/hi2";
import toast from "react-hot-toast";

const MODES = [
  {
    id: "review",
    label: "Review Contract",
    description:
      "Analyze legal contracts — risk assessment, clause extraction, compliance review.",
    icon: <HiOutlineMagnifyingGlass className="text-lg" />,
  },
  {
    id: "draft",
    label: "Create Draft Contract",
    label: "Create Draft Contract",
    description:
      "Generate professional legal contracts with AI-guided templates.",
    icon: <HiOutlinePencilSquare className="text-lg" />,
  },
];

/**
 * StudioPanel — right collapsible panel for mode selection.
 *
 * Props:
 * @param {string|null} activeMode  — 'review' | 'draft' | null
 * @param {Function}    onSetMode   — (modeId) => void
 */
const StudioPanel = ({ activeMode, onSetMode }) => {
  const [collapsed, setCollapsed] = useState(false);

  // State untuk mengontrol animasi denyut (pulse)
  const [isPulsing, setIsPulsing] = useState(false);

  // Effect untuk menjalankan animasi setiap 1 menit
  useEffect(() => {
    const triggerPulse = () => {
      setIsPulsing(true);
      // Matikan animasi setelah 3 detik (cukup untuk beberapa kali denyut)
      setTimeout(() => setIsPulsing(false), 3000);
    };

    // Jalankan sekali saat komponen pertama kali dimuat
    triggerPulse();

    // Set interval setiap 60.000 ms (1 menit)
    const interval = setInterval(() => {
      triggerPulse();
    }, 60000);

    return () => clearInterval(interval); // Bersihkan interval saat komponen di-unmount
  }, []);

  const currentMode = MODES.find((m) => m.id === activeMode);

  const showLegalDisclaimer = (e) => {
    e.stopPropagation(); // Mencegah klik menyebar ke tombol mode
    toast.custom(
      (t) => (
        <div
          className={`${
            t.visible
              ? "animate-enter border-yellow-500/50 dark:border-yellow-600"
              : "animate-leave border-gray-300 dark:border-border"
          } max-w-md w-full bg-white dark:bg-background border  shadow-xl rounded-xl pointer-events-auto flex ring-1 ring-black ring-opacity-5`}
        >
          <div className="flex-1 w-0 p-4">
            <div className="flex items-start">
              <div className="shrink-0 pt-0.5">
                <HiOutlineExclamationCircle className="h-6 w-6 text-yellow-500" />
              </div>
              <div className="ml-3 flex-1">
                <div className="flex">
                  <p className="text-sm w-full font-semibold text-gray-900 dark:text-textPrimary">
                    AI Draft Disclaimer
                  </p>
                  <div className="flex justify-end items-start border-gray-200 dark:border-border">
                    <button
                      onClick={() => toast.dismiss(t.id)}
                      className="p-1 rounded-full cursor-pointer dark:text-textSecondary dark:hover:text-textPrimary
                                               dark:hover:bg-surfaceLight hover:bg-gray-200 transition-colors"
                    >
                      <HiOutlineXMark className="text-base" />
                    </button>
                  </div>
                </div>
                <p className="mt-1 text-sm text-gray-500 dark:text-textSecondary leading-relaxed">
                  Contracts generated by this AI are intended as{" "}
                  <strong>initial drafts</strong> and conceptual references
                  only. They do not constitute formal legal advice. To ensure
                  legal validity, compliance, and security, we strongly
                  recommend reviewing this draft with a qualified legal
                  professional before signing.
                </p>
              </div>
            </div>
          </div>
        </div>
      ),
      { duration: 8000 },
    );
  };

  return (
    <div
      className={`flex flex-col shadow-md bg-white dark:bg-background border border-gray-200 dark:border-border rounded-2xl overflow-hidden
                    transition-all duration-300 shrink-0 h-full
                    ${collapsed ? "w-12" : "w-full lg:w-80"}`}
    >
      {/* ── Header ──────────────────────────────────────────────────────── */}
      <div className="flex items-center px-3 py-3 border-b border-gray-200 dark:border-border shrink-0">
        <button
          onClick={() => setCollapsed((p) => !p)}
          className="p-1.5 rounded-lg cursor-pointer text-gray-500 dark:text-textSecondary hover:text-gray-800 dark:hover:text-textPrimary hover:bg-gray-100 dark:hover:bg-surfaceLight transition-colors"
          aria-label={collapsed ? "Expand panel" : "Collapse panel"}
        >
          {collapsed ? (
            <HiOutlineChevronLeft className="text-base" />
          ) : (
            <HiOutlineChevronRight className="text-base" />
          )}
        </button>
        {!collapsed && (
          <span className="text-gray-800 dark:text-textPrimary text-sm font-semibold ml-2">
            Mode
          </span>
        )}
      </div>

      {/* ── Content ─────────────────────────────────────────────────────── */}
      {collapsed ? (
        // Icon strip
        <div className="flex flex-col items-center py-3 gap-3">
          {MODES.map((m) => (
            <button
              key={m.id}
              onClick={() => onSetMode(m.id)}
              title={m.label}
              className={`p-2 rounded-lg transition-colors relative ${
                activeMode === m.id
                  ? "dark:bg-primary/20 dark:text-primary"
                  : "dark:text-textSecondary hover:text-textPrimary hover:bg-surface"
              }`}
            >
              {m.icon}
              {/* Indikator titik di panel yang di-collapse, juga ikut interval animasi */}
              {m.id === "draft" && (
                <span
                  className={`absolute top-1 right-1 w-2 h-2 bg-yellow-500 rounded-full ${
                    isPulsing ? "animate-pulse" : ""
                  }`}
                />
              )}
            </button>
          ))}
        </div>
      ) : (
        <div className="flex-1 p-3 flex flex-col gap-3 overflow-y-auto">
          {/* Mode cards */}
          {MODES.map((m) => (
            <button
              key={m.id}
              onClick={() => onSetMode(m.id === activeMode ? null : m.id)}
              className={`w-full text-left flex flex-col gap-2 p-3 cursor-pointer rounded-xl border relative
                          transition-all duration-200
                          ${
                            activeMode === m.id
                              ? "dark:bg-primary/15 bg-primary/10 border-primary/40"
                              : "dark:border-border dark:hover:border-primary/30 border-gray-200 hover:bg-gray-200 dark:hover:bg-surface"
                          }`}
            >
              {/* Tombol Info dengan animasi periodik */}
              {m.id === "draft" && (
                <div
                  className="absolute top-3 right-3"
                  onClick={showLegalDisclaimer}
                  title="Important: AI Draft Disclaimer"
                >
                  <HiOutlineExclamationCircle
                    className={`text-xl text-yellow-500 hover:text-yellow-600 transition-colors cursor-pointer drop-shadow-md ${
                      isPulsing ? "animate-pulse" : ""
                    }`}
                  />
                </div>
              )}

              <div className="flex items-center gap-2 pr-6">
                <div
                  className={`p-1.5 rounded-lg transition-colors ${
                    activeMode === m.id
                      ? "dark:bg-primary/30 bg-primary text-white dark:text-primary"
                      : "dark:bg-surfaceLight bg-secondary/30 text-gray-500 dark:text-textSecondary"
                  }`}
                >
                  {m.icon}
                </div>
                <span
                  className={`text-sm font-semibold ${
                    activeMode === m.id
                      ? "dark:text-textPrimary"
                      : "dark:text-textSecondary"
                  }`}
                >
                  {m.label}
                </span>
              </div>
              <p className="text-xs text-gray-700 dark:text-textSecondary leading-relaxed">
                {m.description}
              </p>
            </button>
          ))}

          {/* Active mode indicator */}
          <div className="mt-2 p-3 rounded-xl border border-gray-500 dark:border-border dark:bg-background">
            <div className="flex items-center gap-2 mb-1">
              <span className="w-2 h-2 rounded-full bg-green-400 animate-pulse" />
              <span className="text-xs dark:text-textSecondary font-medium">
                Active Mode
              </span>
            </div>
            <p className="text-xs text-gray-700 dark:text-textPrimary">
              {currentMode
                ? `${currentMode.label} — Upload files and ask questions.`
                : "No mode selected. Choose a mode to get started."}
            </p>
          </div>

          {/* Output placeholder */}
          {!activeMode && (
            <div className="flex-1 flex flex-col items-center justify-center py-8 gap-2 text-center">
              <HiOutlineCheckCircle className="dark:text-textSecondary/30 text-textSecondary text-4xl" />
              <p className="dark:text-textSecondary/60 text-textSecondary text-xs leading-relaxed">
                File output will be saved here.
                <br />
                After adding sources, choose a feature to get started.
              </p>
            </div>
          )}
        </div>
      )}
    </div>
  );
};

export default StudioPanel;
